### ISSUE TITLE
amx file not copied to same directory as pwn file.

### ISSUE THREAD

**Issue by habi498** [dashr9230/Pawno#3]
Hello,
I have a pwn file which i opened with this pawno. Two amx files are created in my computer. One in the same directory as pwn file (gamemodes) and another in the directory of pawno.exe.
The latter works, but the former does not.
What i do is manually copy pasting amx file to my gamemode directory.
It would be great if this problem is fixed.
Also it would be cool to have new/open/edit compile buttons like the samp pawno or the quincy ide.
Thanks

**Comment by dashr9230** [comment]
Thank you for your issue report and suggestion. Now this issue should be fixed and also added the original Pawno style toolbar.

**Comment by habi498** [comment]
Thank you
